export function generatePrintHTML(student) {
    return `<!DOCTYPE html>
<html>
<head>
    <title>${student.name} - Student Profile</title>
    <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1e293b; max-width: 700px; margin: auto; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        .badge { display: inline-block; padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; background: #d1fae5; color: #065f46; }
        .section { margin-top: 24px; border-top: 2px solid #e2e8f0; padding-top: 16px; }
        .section h2 { font-size: 16px; margin-bottom: 12px; }
        .row { display: flex; margin-bottom: 8px; }
        .label { width: 160px; font-size: 13px; color: #64748b; text-transform: uppercase; font-weight: 600; }
        .value { font-size: 14px; font-weight: 500; }
        .contact-card { background: #f8fafc; padding: 12px; border-radius: 8px; margin-bottom: 8px; }
        .chip { display: inline-block; padding: 4px 10px; border-radius: 20px; font-size: 12px; background: #f1f5f9; margin: 2px; }
        @media print { body { padding: 20px; } }
    </style>
</head>
<body>
    <h1>${student.name}</h1>
    <span class="badge">${student.status}</span>
    <p style="color:#64748b;margin-top:4px;">Class ${student.class}-${student.section} | Roll No: ${student.rollNumber} | Blood: ${student.bloodGroup}</p>

    <div class="section">
        <h2>Personal Information</h2>
        <div class="row"><span class="label">Full Name</span><span class="value">${student.name}</span></div>
        <div class="row"><span class="label">Date of Birth</span><span class="value">${new Date(student.dateOfBirth).toLocaleDateString()}</span></div>
        <div class="row"><span class="label">Blood Group</span><span class="value">${student.bloodGroup}</span></div>
        <div class="row"><span class="label">Email</span><span class="value">${student.email}</span></div>
        <div class="row"><span class="label">Phone</span><span class="value">${student.phone}</span></div>
        <div class="row"><span class="label">Address</span><span class="value">${student.address || '—'}</span></div>
    </div>

    <div class="section">
        <h2>Parents & Emergency Contacts</h2>
        ${[...student.parents, ...student.emergencyContacts].map(c => `
            <div class="contact-card">
                <strong>${c.name}</strong> (${c.relationship})<br/>
                <span style="color:#64748b;">${c.phone}</span>
            </div>
        `).join('')}
    </div>

    <div class="section">
        <h2>Medical Information</h2>
        <div class="row"><span class="label">Allergies</span><span class="value">${student.medicalInfo?.allergies?.length ? student.medicalInfo.allergies.map(a => `<span class="chip">${a}</span>`).join('') : '<span class="chip">None</span>'}</span></div>
        <div class="row"><span class="label">Conditions</span><span class="value">${student.medicalInfo?.conditions?.length ? student.medicalInfo.conditions.map(c => `<span class="chip">${c}</span>`).join('') : '<span class="chip">None</span>'}</span></div>
        <div class="row"><span class="label">Medications</span><span class="value">${student.medicalInfo?.medications?.length ? student.medicalInfo.medications.map(m => `<span class="chip">${m}</span>`).join('') : '<span class="chip">None</span>'}</span></div>
        ${student.medicalInfo?.doctor ? `<div class="row"><span class="label">Doctor</span><span class="value">${student.medicalInfo.doctor.name} (${student.medicalInfo.doctor.phone})</span></div>` : ''}
        ${student.medicalInfo?.emergencyInstructions ? `<div class="row"><span class="label">Instructions</span><span class="value">${student.medicalInfo.emergencyInstructions}</span></div>` : ''}
    </div>

    <p style="margin-top:32px;font-size:11px;color:#94a3b8;">Generated by RESQID | ${new Date().toLocaleDateString()}</p>
    <script>window.onload=function(){window.print()}</script>
</body>
</html>`
}

export function printStudentProfile(student) {
    const html = generatePrintHTML(student)
    const w = window.open('', '_blank', 'width=800,height=600')
    if (w) { w.document.write(html); w.document.close() }
}