// ── CLASSES ──
export const MOCK_CLASSES = [
  {
    id: "c1",
    grade: "Nursery",
    section: "A",
    classTeacher: "Mrs. Meena Pillai",
    students: 30,
    subjects: ["English", "Hindi", "Maths"],
    room: "R-01",
    status: "Active",
  },
  {
    id: "c2",
    grade: "Nursery",
    section: "B",
    classTeacher: "Mrs. Rekha Sharma",
    students: 28,
    subjects: ["English", "Hindi", "Maths"],
    room: "R-02",
    status: "Active",
  },
  {
    id: "c3",
    grade: "LKG",
    section: "A",
    classTeacher: "Ms. Anita Joshi",
    students: 32,
    subjects: ["English", "Hindi", "Maths", "EVS"],
    room: "R-03",
    status: "Active",
  },
  {
    id: "c4",
    grade: "Cls 1",
    section: "A",
    classTeacher: "Mrs. Kavita Reddy",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "EVS", "Arts"],
    room: "R-10",
    status: "Active",
  },
  {
    id: "c5",
    grade: "Cls 1",
    section: "B",
    classTeacher: "Mr. Rajesh Nair",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "EVS"],
    room: "R-11",
    status: "Active",
  },
  {
    id: "c6",
    grade: "Cls 5",
    section: "A",
    classTeacher: "Mrs. Sunita Das",
    students: 38,
    subjects: ["English", "Hindi", "Maths", "Science", "Social"],
    room: "R-20",
    status: "Active",
  },
  {
    id: "c7",
    grade: "Cls 6",
    section: "A",
    classTeacher: "Mr. Arjun Verma",
    students: 36,
    subjects: ["English", "Hindi", "Maths", "Science", "History", "Geography"],
    room: "R-30",
    status: "Active",
  },
  {
    id: "c8",
    grade: "Cls 6",
    section: "B",
    classTeacher: "Ms. Divya Joshi",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "Science", "History"],
    room: "R-31",
    status: "Active",
  },
  {
    id: "c9",
    grade: "Cls 7",
    section: "A",
    classTeacher: "Mr. Suresh Kumar",
    students: 35,
    subjects: ["Mathematics", "English", "Science", "History", "Geography"],
    room: "R-32",
    status: "Active",
  },
  {
    id: "c10",
    grade: "Cls 7",
    section: "B",
    classTeacher: "Ms. Priya Nair",
    students: 35,
    subjects: ["Mathematics", "English", "Science", "History"],
    room: "R-33",
    status: "Active",
  },
  {
    id: "c11",
    grade: "Cls 7",
    section: "C",
    classTeacher: "Mr. Vikram Mehta",
    students: 33,
    subjects: ["Mathematics", "English", "Science", "History", "CS"],
    room: "R-34",
    status: "Active",
  },
  {
    id: "c12",
    grade: "Cls 8",
    section: "A",
    classTeacher: "Mrs. Ananya Reddy",
    students: 34,
    subjects: ["Mathematics", "English", "Science", "History", "CS"],
    room: "R-40",
    status: "Active",
  },
  {
    id: "c13",
    grade: "Cls 9",
    section: "A",
    classTeacher: "Mr. Amit Das",
    students: 33,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "Biology"],
    room: "R-50",
    status: "Active",
  },
  {
    id: "c14",
    grade: "Cls 9",
    section: "B",
    classTeacher: "Mrs. Geeta Sharma",
    students: 32,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "CS"],
    room: "R-51",
    status: "Active",
  },
  {
    id: "c15",
    grade: "Cls 10",
    section: "A",
    classTeacher: "Mr. Suresh Kumar",
    students: 32,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "Biology"],
    room: "R-52",
    status: "Active",
  },
  {
    id: "c16",
    grade: "Cls 11",
    section: "A",
    classTeacher: "Dr. Suresh Nair",
    students: 30,
    subjects: ["Physics", "Chemistry", "Mathematics", "English"],
    room: "R-60",
    status: "Active",
  },
  {
    id: "c17",
    grade: "Cls 11",
    section: "B",
    classTeacher: "Ms. Sunita Roy",
    students: 28,
    subjects: ["Biology", "Chemistry", "Mathematics", "English"],
    room: "R-61",
    status: "Active",
  },
  {
    id: "c18",
    grade: "Cls 12",
    section: "A",
    classTeacher: "Mr. Arjun Verma",
    students: 27,
    subjects: ["Physics", "Chemistry", "Mathematics", "English"],
    room: "R-62",
    status: "Active",
  },
  {
    id: "c19",
    grade: "Cls 12",
    section: "B",
    classTeacher: "Mrs. Meera Shah",
    students: 25,
    subjects: ["Biology", "Chemistry", "Mathematics", "English"],
    room: "R-63",
    status: "Inactive",
  },
];

// ── ANOMALIES (Emergency Module) ──
export const MOCK_ANOMALIES = [
  {
    id: "ANO-001",
    type: "duplicate_scan",
    severity: "high",
    status: "open",
    student: "Priya Sharma",
    studentId: "STU-2341",
    class: "Class 8-A",
    avatar: "PS",
    avatarColor: "bg-blue-500",
    description:
      "QR card scanned twice within 4 minutes at two different gates",
    location: "Gate A → Gate C",
    time: "8:02 AM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-002",
    type: "unknown_card",
    severity: "high",
    status: "open",
    student: "Unknown",
    studentId: null,
    class: "—",
    avatar: "?",
    avatarColor: "bg-slate-400",
    description: "Unregistered QR card scanned at main entrance",
    location: "Main Entrance",
    time: "8:17 AM",
    date: "Today",
    detectedBy: "Gate Scanner #1",
  },
  {
    id: "ANO-003",
    type: "outside_hours",
    severity: "medium",
    status: "open",
    student: "Rahul Gupta",
    studentId: "STU-1892",
    class: "Class 11-B",
    avatar: "RG",
    avatarColor: "bg-indigo-500",
    description: "Student scanned card 2 hours after school ended",
    location: "Back Gate",
    time: "5:45 PM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-004",
    type: "multiple_exits",
    severity: "medium",
    status: "investigating",
    student: "Dev Chatterjee",
    studentId: "STU-4201",
    class: "Class 9-B",
    avatar: "DC",
    avatarColor: "bg-amber-500",
    description:
      "Student recorded exiting campus 3 times in one day without re-entry",
    location: "Gate B",
    time: "11:30 AM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-005",
    type: "suspicious_timing",
    severity: "low",
    status: "open",
    student: "Sneha Bose",
    studentId: "STU-3012",
    class: "Class 7-C",
    avatar: "SB",
    avatarColor: "bg-rose-500",
    description: "Card scanned 35 minutes before school gates officially open",
    location: "Main Entrance",
    time: "6:55 AM",
    date: "Today",
    detectedBy: "Gate Scanner #1",
  },
];
