// ── CLASSES ──
export const MOCK_CLASSES = [
  {
    id: "c1",
    grade: "Nursery",
    section: "A",
    classTeacher: "Mrs. Meena Pillai",
    students: 30,
    subjects: ["English", "Hindi", "Maths"],
    room: "R-01",
    status: "Active",
  },
  {
    id: "c2",
    grade: "Nursery",
    section: "B",
    classTeacher: "Mrs. Rekha Sharma",
    students: 28,
    subjects: ["English", "Hindi", "Maths"],
    room: "R-02",
    status: "Active",
  },
  {
    id: "c3",
    grade: "LKG",
    section: "A",
    classTeacher: "Ms. Anita Joshi",
    students: 32,
    subjects: ["English", "Hindi", "Maths", "EVS"],
    room: "R-03",
    status: "Active",
  },
  {
    id: "c4",
    grade: "Cls 1",
    section: "A",
    classTeacher: "Mrs. Kavita Reddy",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "EVS", "Arts"],
    room: "R-10",
    status: "Active",
  },
  {
    id: "c5",
    grade: "Cls 1",
    section: "B",
    classTeacher: "Mr. Rajesh Nair",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "EVS"],
    room: "R-11",
    status: "Active",
  },
  {
    id: "c6",
    grade: "Cls 5",
    section: "A",
    classTeacher: "Mrs. Sunita Das",
    students: 38,
    subjects: ["English", "Hindi", "Maths", "Science", "Social"],
    room: "R-20",
    status: "Active",
  },
  {
    id: "c7",
    grade: "Cls 6",
    section: "A",
    classTeacher: "Mr. Arjun Verma",
    students: 36,
    subjects: ["English", "Hindi", "Maths", "Science", "History", "Geography"],
    room: "R-30",
    status: "Active",
  },
  {
    id: "c8",
    grade: "Cls 6",
    section: "B",
    classTeacher: "Ms. Divya Joshi",
    students: 35,
    subjects: ["English", "Hindi", "Maths", "Science", "History"],
    room: "R-31",
    status: "Active",
  },
  {
    id: "c9",
    grade: "Cls 7",
    section: "A",
    classTeacher: "Mr. Suresh Kumar",
    students: 35,
    subjects: ["Mathematics", "English", "Science", "History", "Geography"],
    room: "R-32",
    status: "Active",
  },
  {
    id: "c10",
    grade: "Cls 7",
    section: "B",
    classTeacher: "Ms. Priya Nair",
    students: 35,
    subjects: ["Mathematics", "English", "Science", "History"],
    room: "R-33",
    status: "Active",
  },
  {
    id: "c11",
    grade: "Cls 7",
    section: "C",
    classTeacher: "Mr. Vikram Mehta",
    students: 33,
    subjects: ["Mathematics", "English", "Science", "History", "CS"],
    room: "R-34",
    status: "Active",
  },
  {
    id: "c12",
    grade: "Cls 8",
    section: "A",
    classTeacher: "Mrs. Ananya Reddy",
    students: 34,
    subjects: ["Mathematics", "English", "Science", "History", "CS"],
    room: "R-40",
    status: "Active",
  },
  {
    id: "c13",
    grade: "Cls 9",
    section: "A",
    classTeacher: "Mr. Amit Das",
    students: 33,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "Biology"],
    room: "R-50",
    status: "Active",
  },
  {
    id: "c14",
    grade: "Cls 9",
    section: "B",
    classTeacher: "Mrs. Geeta Sharma",
    students: 32,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "CS"],
    room: "R-51",
    status: "Active",
  },
  {
    id: "c15",
    grade: "Cls 10",
    section: "A",
    classTeacher: "Mr. Suresh Kumar",
    students: 32,
    subjects: ["Mathematics", "English", "Physics", "Chemistry", "Biology"],
    room: "R-52",
    status: "Active",
  },
  {
    id: "c16",
    grade: "Cls 11",
    section: "A",
    classTeacher: "Dr. Suresh Nair",
    students: 30,
    subjects: ["Physics", "Chemistry", "Mathematics", "English"],
    room: "R-60",
    status: "Active",
  },
  {
    id: "c17",
    grade: "Cls 11",
    section: "B",
    classTeacher: "Ms. Sunita Roy",
    students: 28,
    subjects: ["Biology", "Chemistry", "Mathematics", "English"],
    room: "R-61",
    status: "Active",
  },
  {
    id: "c18",
    grade: "Cls 12",
    section: "A",
    classTeacher: "Mr. Arjun Verma",
    students: 27,
    subjects: ["Physics", "Chemistry", "Mathematics", "English"],
    room: "R-62",
    status: "Active",
  },
  {
    id: "c19",
    grade: "Cls 12",
    section: "B",
    classTeacher: "Mrs. Meera Shah",
    students: 25,
    subjects: ["Biology", "Chemistry", "Mathematics", "English"],
    room: "R-63",
    status: "Inactive",
  },
];

export const MOCK_SUBJECTS = [
  {
    id: "sub1",
    name: "Mathematics",
    code: "MATH101",
    category: "Core",
    description:
      "Algebra, Geometry, Trigonometry, Statistics, and Calculus fundamentals",
    periodsPerWeek: 5,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mr. Suresh Kumar", "Ms. Priya Nair"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mr. Suresh Kumar"],
      },
      {
        classId: "c9",
        grade: "Cls 7",
        section: "A",
        teachers: ["Ms. Priya Nair", "Dr. Amit Das"],
      },
      {
        classId: "c10",
        grade: "Cls 7",
        section: "B",
        teachers: ["Ms. Priya Nair"],
      },
      {
        classId: "c11",
        grade: "Cls 7",
        section: "C",
        teachers: ["Mr. Vikram Mehta"],
      },
      {
        classId: "c12",
        grade: "Cls 8",
        section: "A",
        teachers: ["Mr. Suresh Kumar"],
      },
      {
        classId: "c13",
        grade: "Cls 9",
        section: "A",
        teachers: ["Dr. Amit Das"],
      },
      {
        classId: "c14",
        grade: "Cls 9",
        section: "B",
        teachers: ["Dr. Amit Das", "Ms. Priya Nair"],
      },
    ],
  },
  {
    id: "sub2",
    name: "English",
    code: "ENG101",
    category: "Language",
    description: "Grammar, Literature, Composition, and Reading Comprehension",
    periodsPerWeek: 6,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mrs. Ananya Reddy"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mrs. Ananya Reddy"],
      },
      {
        classId: "c9",
        grade: "Cls 7",
        section: "A",
        teachers: ["Mr. Arjun Verma"],
      },
      {
        classId: "c10",
        grade: "Cls 7",
        section: "B",
        teachers: ["Mr. Arjun Verma"],
      },
      {
        classId: "c11",
        grade: "Cls 7",
        section: "C",
        teachers: ["Mrs. Ananya Reddy"],
      },
      {
        classId: "c12",
        grade: "Cls 8",
        section: "A",
        teachers: ["Mr. Arjun Verma"],
      },
    ],
  },
  {
    id: "sub3",
    name: "Science",
    code: "SCI101",
    category: "Core",
    description: "Physics, Chemistry, and Biology fundamentals",
    periodsPerWeek: 5,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mrs. Kavita Reddy"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mrs. Kavita Reddy"],
      },
      {
        classId: "c9",
        grade: "Cls 7",
        section: "A",
        teachers: ["Mrs. Geeta Sharma"],
      },
      {
        classId: "c10",
        grade: "Cls 7",
        section: "B",
        teachers: ["Mrs. Geeta Sharma"],
      },
    ],
  },
  {
    id: "sub4",
    name: "Computer Science",
    code: "CS101",
    category: "Elective",
    description: "Programming fundamentals, Python, Web Development basics",
    periodsPerWeek: 3,
    status: "Active",
    mappings: [
      {
        classId: "c11",
        grade: "Cls 7",
        section: "C",
        teachers: ["Mr. Rajesh Nair"],
      },
      {
        classId: "c12",
        grade: "Cls 8",
        section: "A",
        teachers: ["Mr. Rajesh Nair"],
      },
      {
        classId: "c13",
        grade: "Cls 9",
        section: "A",
        teachers: ["Mr. Rajesh Nair"],
      },
      {
        classId: "c14",
        grade: "Cls 9",
        section: "B",
        teachers: ["Mr. Amit Das"],
      },
    ],
  },
  {
    id: "sub5",
    name: "Hindi",
    code: "HIN101",
    category: "Language",
    description: "Hindi literature, grammar, and creative writing",
    periodsPerWeek: 4,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mrs. Sunita Das"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mrs. Sunita Das"],
      },
      {
        classId: "c9",
        grade: "Cls 7",
        section: "A",
        teachers: ["Mrs. Meena Pillai"],
      },
    ],
  },
  {
    id: "sub6",
    name: "History",
    code: "HIS101",
    category: "Core",
    description: "Ancient civilizations, Medieval India, Modern history",
    periodsPerWeek: 3,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mr. Vikram Mehta"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mr. Vikram Mehta"],
      },
      {
        classId: "c9",
        grade: "Cls 7",
        section: "A",
        teachers: ["Mrs. Rekha Sharma"],
      },
    ],
  },
  {
    id: "sub7",
    name: "Physical Education",
    code: "PE101",
    category: "Activity",
    description: "Sports, physical fitness, and health education",
    periodsPerWeek: 2,
    status: "Active",
    mappings: [
      {
        classId: "c7",
        grade: "Cls 6",
        section: "A",
        teachers: ["Mr. Arjun Verma"],
      },
      {
        classId: "c8",
        grade: "Cls 6",
        section: "B",
        teachers: ["Mr. Arjun Verma"],
      },
      {
        classId: "c13",
        grade: "Cls 9",
        section: "A",
        teachers: ["Mr. Suresh Kumar"],
      },
    ],
  },
  {
    id: "sub8",
    name: "Arts & Craft",
    code: "ART101",
    category: "Activity",
    description: "Drawing, painting, and creative crafts",
    periodsPerWeek: 2,
    status: "Inactive",
    mappings: [
      {
        classId: "c4",
        grade: "Cls 1",
        section: "A",
        teachers: ["Mrs. Anita Joshi"],
      },
    ],
  },
];

export const MOCK_TEACHERS = [
  {
    id: "t1",
    name: "Mrs. Meena Pillai",
    email: "meena.p@school.in",
    phone: "9876543210",
    avatar: "MP",
    avatarColor: "bg-blue-500",
    gender: "Female",
    subjects: ["Mathematics", "Physics"],
    qualification: "M.Sc, B.Ed",
    experience: "8 years",
    joiningDate: "2016-06-15",
    employeeId: "EMP-2016-042",
    status: "maternity",
    maxPeriodsPerDay: 5,
    currentLoad: 24,
    maxLoad: 30,
    wellness: {
      type: "maternity",
      startDate: "2026-01-15",
      expectedEndDate: "2026-07-15",
      notes: "Third trimester onwards",
      requiresReplacement: true,
    },
    replacement: "t4",
    substituteFor: [],
    schedule: [
      {
        day: "Mon",
        period: 1,
        class: "Cls 6-A",
        subject: "Mathematics",
        room: "R-30",
        type: "regular",
      },
      {
        day: "Mon",
        period: 2,
        class: "Cls 9-A",
        subject: "Physics",
        room: "R-50",
        type: "regular",
      },
      {
        day: "Tue",
        period: 1,
        class: "Cls 7-A",
        subject: "Mathematics",
        room: "R-32",
        type: "regular",
      },
      {
        day: "Wed",
        period: 3,
        class: "Cls 6-A",
        subject: "Mathematics",
        room: "R-30",
        type: "regular",
      },
      {
        day: "Thu",
        period: 1,
        class: "Cls 6-A",
        subject: "Mathematics",
        room: "R-30",
        type: "regular",
      },
      {
        day: "Thu",
        period: 2,
        class: "Cls 9-A",
        subject: "Physics",
        room: "R-50",
        type: "regular",
      },
      {
        day: "Fri",
        period: 4,
        class: "Cls 7-A",
        subject: "Mathematics",
        room: "R-32",
        type: "regular",
      },
    ],
  },
  {
    id: "t2",
    name: "Mr. Suresh Kumar",
    email: "suresh.k@school.in",
    phone: "9876543211",
    avatar: "SK",
    avatarColor: "bg-indigo-500",
    gender: "Male",
    subjects: ["Mathematics", "Science"],
    qualification: "M.Sc, M.Ed",
    experience: "12 years",
    joiningDate: "2012-03-10",
    employeeId: "EMP-2012-018",
    status: "active",
    maxPeriodsPerDay: 5,
    currentLoad: 28,
    maxLoad: 30,
    wellness: null,
    replacement: null,
    substituteFor: ["t1"],
    schedule: [
      {
        day: "Mon",
        period: 1,
        class: "Cls 7-A",
        subject: "Mathematics",
        room: "R-32",
        type: "substitute",
      },
      {
        day: "Mon",
        period: 3,
        class: "Cls 8-A",
        subject: "Mathematics",
        room: "R-40",
        type: "regular",
      },
      {
        day: "Tue",
        period: 2,
        class: "Cls 9-A",
        subject: "Science",
        room: "R-52",
        type: "regular",
      },
      {
        day: "Wed",
        period: 1,
        class: "Cls 7-A",
        subject: "Mathematics",
        room: "R-32",
        type: "regular",
      },
      {
        day: "Wed",
        period: 2,
        class: "Cls 8-A",
        subject: "Science",
        room: "R-40",
        type: "regular",
      },
      {
        day: "Thu",
        period: 3,
        class: "Cls 7-A",
        subject: "Mathematics",
        room: "R-32",
        type: "substitute",
      },
      {
        day: "Fri",
        period: 1,
        class: "Cls 8-A",
        subject: "Mathematics",
        room: "R-40",
        type: "regular",
      },
    ],
  },
  {
    id: "t3",
    name: "Ms. Priya Nair",
    email: "priya.n@school.in",
    phone: "9876543212",
    avatar: "PN",
    avatarColor: "bg-pink-500",
    gender: "Female",
    subjects: ["Mathematics", "English"],
    qualification: "M.A, B.Ed",
    experience: "5 years",
    joiningDate: "2019-07-22",
    employeeId: "EMP-2019-031",
    status: "active",
    maxPeriodsPerDay: 5,
    currentLoad: 22,
    maxLoad: 28,
    wellness: null,
    replacement: null,
    substituteFor: [],
    schedule: [
      {
        day: "Mon",
        period: 2,
        class: "Cls 7-B",
        subject: "Mathematics",
        room: "R-33",
        type: "regular",
      },
      {
        day: "Tue",
        period: 3,
        class: "Cls 7-B",
        subject: "Mathematics",
        room: "R-33",
        type: "regular",
      },
      {
        day: "Wed",
        period: 4,
        class: "Cls 6-B",
        subject: "English",
        room: "R-31",
        type: "regular",
      },
      {
        day: "Thu",
        period: 2,
        class: "Cls 7-B",
        subject: "Mathematics",
        room: "R-33",
        type: "regular",
      },
      {
        day: "Fri",
        period: 2,
        class: "Cls 6-B",
        subject: "English",
        room: "R-31",
        type: "regular",
      },
    ],
  },
  {
    id: "t4",
    name: "Dr. Amit Das",
    email: "amit.d@school.in",
    phone: "9876543213",
    avatar: "AD",
    avatarColor: "bg-violet-500",
    gender: "Male",
    subjects: ["Mathematics", "Physics", "Chemistry"],
    qualification: "Ph.D, M.Ed",
    experience: "15 years",
    joiningDate: "2009-04-05",
    employeeId: "EMP-2009-005",
    status: "active",
    maxPeriodsPerDay: 5,
    currentLoad: 20,
    maxLoad: 32,
    wellness: null,
    replacement: null,
    substituteFor: ["t1"],
    schedule: [
      {
        day: "Mon",
        period: 2,
        class: "Cls 9-A",
        subject: "Physics",
        room: "R-50",
        type: "substitute",
      },
      {
        day: "Tue",
        period: 4,
        class: "Cls 9-B",
        subject: "Physics",
        room: "R-51",
        type: "regular",
      },
      {
        day: "Wed",
        period: 3,
        class: "Cls 6-A",
        subject: "Mathematics",
        room: "R-30",
        type: "substitute",
      },
      {
        day: "Thu",
        period: 2,
        class: "Cls 9-A",
        subject: "Physics",
        room: "R-50",
        type: "substitute",
      },
      {
        day: "Fri",
        period: 3,
        class: "Cls 9-B",
        subject: "Chemistry",
        room: "R-51",
        type: "regular",
      },
    ],
  },
  {
    id: "t5",
    name: "Mrs. Sunita Das",
    email: "sunita.d@school.in",
    phone: "9876543214",
    avatar: "SD",
    avatarColor: "bg-orange-500",
    gender: "Female",
    subjects: ["Hindi", "English"],
    qualification: "M.A, B.Ed",
    experience: "10 years",
    joiningDate: "2014-08-18",
    employeeId: "EMP-2014-025",
    status: "medical",
    maxPeriodsPerDay: 5,
    currentLoad: 15,
    maxLoad: 28,
    wellness: {
      type: "medical",
      startDate: "2026-05-20",
      expectedEndDate: "2026-06-20",
      notes: "Post-surgery recovery",
      requiresReplacement: true,
    },
    replacement: null,
    substituteFor: [],
    schedule: [
      {
        day: "Mon",
        period: 3,
        class: "Cls 5-A",
        subject: "Hindi",
        room: "R-20",
        type: "regular",
      },
      {
        day: "Tue",
        period: 1,
        class: "Cls 6-A",
        subject: "Hindi",
        room: "R-30",
        type: "regular",
      },
      {
        day: "Wed",
        period: 2,
        class: "Cls 5-A",
        subject: "Hindi",
        room: "R-20",
        type: "regular",
      },
    ],
  },
  {
    id: "t6",
    name: "Mr. Rajesh Nair",
    email: "rajesh.n@school.in",
    phone: "9876543215",
    avatar: "RN",
    avatarColor: "bg-emerald-500",
    gender: "Male",
    subjects: ["Computer Science", "Mathematics"],
    qualification: "B.Tech, M.Ed",
    experience: "6 years",
    joiningDate: "2018-02-14",
    employeeId: "EMP-2018-012",
    status: "active",
    maxPeriodsPerDay: 5,
    currentLoad: 18,
    maxLoad: 26,
    wellness: null,
    replacement: null,
    substituteFor: ["t5"],
    schedule: [
      {
        day: "Mon",
        period: 4,
        class: "Cls 7-C",
        subject: "Computer Science",
        room: "R-34",
        type: "regular",
      },
      {
        day: "Tue",
        period: 2,
        class: "Cls 5-A",
        subject: "Hindi",
        room: "R-20",
        type: "substitute",
      },
      {
        day: "Wed",
        period: 1,
        class: "Cls 8-A",
        subject: "Computer Science",
        room: "R-40",
        type: "regular",
      },
      {
        day: "Thu",
        period: 4,
        class: "Cls 7-C",
        subject: "Computer Science",
        room: "R-34",
        type: "regular",
      },
      {
        day: "Fri",
        period: 1,
        class: "Cls 5-A",
        subject: "Hindi",
        room: "R-20",
        type: "substitute",
      },
    ],
  },
];

export const MOCK_TIMETABLE = {
  id: "tt-2026-term1",
  academicYear: "2026-2027",
  term: "Term 1",
  status: "draft",
  generatedAt: "2026-06-05",
  classes: ["c7", "c8", "c9", "c10", "c12", "c13"],
  slots: [
    // Monday
    {
      day: "Mon",
      period: 1,
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      subject: "Mathematics",
      teacherId: "t1",
      teacherName: "Mrs. Meena Pillai",
      room: "R-30",
    },
    {
      day: "Mon",
      period: 1,
      classId: "c8",
      grade: "Cls 6",
      section: "B",
      subject: "English",
      teacherId: "t2",
      teacherName: "Mr. Suresh Kumar",
      room: "R-31",
    },
    {
      day: "Mon",
      period: 1,
      classId: "c9",
      grade: "Cls 7",
      section: "A",
      subject: "Science",
      teacherId: "t3",
      teacherName: "Ms. Priya Nair",
      room: "R-32",
    },
    {
      day: "Mon",
      period: 2,
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      subject: "English",
      teacherId: "t2",
      teacherName: "Mr. Suresh Kumar",
      room: "R-30",
    },
    {
      day: "Mon",
      period: 2,
      classId: "c8",
      grade: "Cls 6",
      section: "B",
      subject: "Mathematics",
      teacherId: "t1",
      teacherName: "Mrs. Meena Pillai",
      room: "R-31",
    },
    {
      day: "Mon",
      period: 2,
      classId: "c9",
      grade: "Cls 7",
      section: "A",
      subject: "Mathematics",
      teacherId: "t4",
      teacherName: "Dr. Amit Das",
      room: "R-32",
    },
    {
      day: "Mon",
      period: 3,
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      subject: "Science",
      teacherId: "t3",
      teacherName: "Ms. Priya Nair",
      room: "R-30",
    },
    {
      day: "Mon",
      period: 3,
      classId: "c8",
      grade: "Cls 6",
      section: "B",
      subject: "Hindi",
      teacherId: "t5",
      teacherName: "Mrs. Sunita Das",
      room: "R-31",
    },
    // Tuesday
    {
      day: "Tue",
      period: 1,
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      subject: "Hindi",
      teacherId: "t5",
      teacherName: "Mrs. Sunita Das",
      room: "R-30",
    },
    {
      day: "Tue",
      period: 1,
      classId: "c9",
      grade: "Cls 7",
      section: "A",
      subject: "Mathematics",
      teacherId: "t1",
      teacherName: "Mrs. Meena Pillai",
      room: "R-32",
    },
    {
      day: "Tue",
      period: 2,
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      subject: "Mathematics",
      teacherId: "t1",
      teacherName: "Mrs. Meena Pillai",
      room: "R-30",
    },
    {
      day: "Tue",
      period: 2,
      classId: "c8",
      grade: "Cls 6",
      section: "B",
      subject: "Science",
      teacherId: "t3",
      teacherName: "Ms. Priya Nair",
      room: "R-31",
    },
  ],
  issues: [
    {
      id: "err1",
      type: "teacher_conflict",
      severity: "error",
      class: "Cls 7-A",
      day: "Mon",
      period: 2,
      description: "Dr. Amit Das assigned but not in wellness replacement list",
      resolved: false,
    },
    {
      id: "err2",
      type: "room_clash",
      severity: "error",
      class: "Cls 6-A",
      day: "Tue",
      period: 1,
      description: "Room R-30 double-booked with Cls 6-B",
      resolved: false,
    },
    {
      id: "warn1",
      type: "teacher_overload",
      severity: "warning",
      class: "—",
      day: "—",
      period: null,
      description: "Mrs. Meena Pillai has 32/30 assigned periods",
      resolved: false,
    },
    {
      id: "warn2",
      type: "gap_period",
      severity: "warning",
      class: "Cls 7-A",
      day: "Mon",
      period: null,
      description: "Cls 7-A has a gap between P3 and P5 on Monday",
      resolved: false,
    },
    {
      id: "warn3",
      type: "no_lunch",
      severity: "warning",
      class: "Cls 9-A",
      day: "—",
      period: null,
      description: "No lunch break assigned for Cls 9-A",
      resolved: false,
    },
    {
      id: "info1",
      type: "unused_capacity",
      severity: "info",
      class: "—",
      day: "—",
      period: null,
      description: "Mr. Rajesh Nair has only 18/26 assigned periods",
      resolved: false,
    },
  ],
};

export const MOCK_ATTENDANCE_TODAY = {
  date: "2026-06-05",
  totalStudents: 542,
  present: 487,
  absent: 38,
  late: 17,
  classes: [
    {
      classId: "c7",
      grade: "Cls 6",
      section: "A",
      total: 36,
      present: 34,
      absent: 1,
      late: 1,
      percentage: 94,
    },
    {
      classId: "c8",
      grade: "Cls 6",
      section: "B",
      total: 35,
      present: 32,
      absent: 2,
      late: 1,
      percentage: 91,
    },
    {
      classId: "c9",
      grade: "Cls 7",
      section: "A",
      total: 35,
      present: 30,
      absent: 4,
      late: 1,
      percentage: 86,
    },
    {
      classId: "c10",
      grade: "Cls 7",
      section: "B",
      total: 35,
      present: 33,
      absent: 1,
      late: 1,
      percentage: 94,
    },
    {
      classId: "c12",
      grade: "Cls 8",
      section: "A",
      total: 34,
      present: 31,
      absent: 2,
      late: 1,
      percentage: 91,
    },
    {
      classId: "c13",
      grade: "Cls 9",
      section: "A",
      total: 33,
      present: 28,
      absent: 4,
      late: 1,
      percentage: 85,
    },
  ],
};

export const MOCK_RFID_LOGS = [
  {
    id: "log1",
    studentName: "Aarav Sharma",
    class: "Cls 6-A",
    rollNo: 1,
    cardId: "RFID-001",
    tapIn: "8:12 AM",
    tapOut: "2:05 PM",
    gate: "Main Gate",
    status: "success",
    date: "Today",
  },
  {
    id: "log2",
    studentName: "Ananya Patel",
    class: "Cls 6-A",
    rollNo: 2,
    cardId: "RFID-002",
    tapIn: "8:14 AM",
    tapOut: "2:02 PM",
    gate: "Main Gate",
    status: "success",
    date: "Today",
  },
  {
    id: "log3",
    studentName: "Arjun Nair",
    class: "Cls 6-A",
    rollNo: 3,
    cardId: "RFID-003",
    tapIn: "9:05 AM",
    tapOut: "2:00 PM",
    gate: "Side Gate",
    status: "late",
    date: "Today",
  },
  {
    id: "log4",
    studentName: "Diya Reddy",
    class: "Cls 6-A",
    rollNo: 4,
    cardId: "RFID-004",
    tapIn: "8:10 AM",
    tapOut: "2:08 PM",
    gate: "Main Gate",
    status: "success",
    date: "Today",
  },
  {
    id: "log5",
    studentName: "Ishaan Gupta",
    class: "Cls 6-A",
    rollNo: 5,
    cardId: "RFID-005",
    tapIn: null,
    tapOut: null,
    gate: "—",
    status: "absent",
    date: "Today",
  },
  {
    id: "log6",
    studentName: "Unknown Card",
    class: "—",
    rollNo: null,
    cardId: "UNREG-042",
    tapIn: "8:17 AM",
    tapOut: null,
    gate: "Main Gate",
    status: "failed",
    date: "Today",
  },
  {
    id: "log7",
    studentName: "Priya Sharma",
    class: "Cls 8-A",
    rollNo: 12,
    cardId: "RFID-042",
    tapIn: "8:00 AM",
    tapOut: "8:04 AM",
    gate: "Gate A → Gate C",
    status: "duplicate",
    date: "Today",
  },
];

export const MOCK_DEVICES = [
  {
    id: "dev1",
    name: "Main Gate Scanner",
    type: "RFID",
    location: "Main Entrance",
    status: "online",
    lastSync: "2 min ago",
    battery: 92,
    firmware: "v2.4.1",
    totalScans: 487,
  },
  {
    id: "dev2",
    name: "Side Gate Scanner",
    type: "RFID",
    location: "Side Entrance",
    status: "online",
    lastSync: "1 min ago",
    battery: 78,
    firmware: "v2.4.1",
    totalScans: 112,
  },
  {
    id: "dev3",
    name: "Back Gate Scanner",
    type: "RFID",
    location: "Back Gate",
    status: "offline",
    lastSync: "2 hours ago",
    battery: 23,
    firmware: "v2.3.0",
    totalScans: 45,
  },
  {
    id: "dev4",
    name: "Gate A Scanner",
    type: "QR/RFID",
    location: "Gate A",
    status: "online",
    lastSync: "30 sec ago",
    battery: 95,
    firmware: "v2.4.1",
    totalScans: 320,
  },
];

export const MOCK_CARDS = [
  {
    id: "card_001",
    cardNumber: "RESQID-2024-0001",
    qrCodeId: "RESQID-STU-2024-001234",
    studentId: "stu1",
    studentName: "Aarav Sharma",
    class: "10",
    section: "A",
    rollNo: "24",
    bloodGroup: "O+",
    status: "active",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-01-20",
    printCount: 1,
    history: [{ date: "2024-01-20", action: "issued", note: "First batch" }],
  },
  {
    id: "card_002",
    cardNumber: "RESQID-2024-0002",
    qrCodeId: "RESQID-STU-2024-001235",
    studentId: "stu2",
    studentName: "Ananya Patel",
    class: "9",
    section: "B",
    rollNo: "15",
    bloodGroup: "B+",
    status: "active",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-01-20",
    printCount: 1,
    history: [{ date: "2024-01-20", action: "issued", note: "First batch" }],
  },
  {
    id: "card_003",
    cardNumber: "RESQID-2024-0003",
    qrCodeId: "RESQID-STU-2024-001236",
    studentId: "stu3",
    studentName: "Arjun Nair",
    class: "8",
    section: "A",
    rollNo: "8",
    bloodGroup: "A+",
    status: "lost",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-01-20",
    printCount: 1,
    history: [
      { date: "2024-01-20", action: "issued", note: "First batch" },
      { date: "2024-06-15", action: "lost", note: "Reported lost by parent" },
    ],
  },
  {
    id: "card_004",
    cardNumber: "RESQID-2024-0004",
    qrCodeId: "RESQID-STU-2024-001237",
    studentId: "stu4",
    studentName: "Diya Reddy",
    class: "10",
    section: "B",
    rollNo: "31",
    bloodGroup: "AB+",
    status: "active",
    issuedDate: "2024-01-21",
    lastPrinted: "2024-01-21",
    printCount: 1,
    history: [{ date: "2024-01-21", action: "issued", note: "First batch" }],
  },
  {
    id: "card_005",
    cardNumber: "RESQID-2024-0005",
    qrCodeId: "RESQID-STU-2024-001238",
    studentId: "stu5",
    studentName: "Ishaan Gupta",
    class: "7",
    section: "C",
    rollNo: "12",
    bloodGroup: "O-",
    status: "replaced",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-06-16",
    printCount: 2,
    history: [
      { date: "2024-01-20", action: "issued", note: "First batch" },
      { date: "2024-06-15", action: "lost", note: "Reported lost" },
      {
        date: "2024-06-16",
        action: "replaced",
        note: "New card RESQID-2024-0042",
      },
    ],
  },
  {
    id: "card_006",
    cardNumber: "RESQID-2024-0006",
    qrCodeId: "RESQID-STU-2024-001239",
    studentId: "stu6",
    studentName: "Kavya Joshi",
    class: "10",
    section: "A",
    rollNo: "5",
    bloodGroup: "B-",
    status: "active",
    issuedDate: "2024-02-01",
    lastPrinted: "2024-02-01",
    printCount: 1,
    history: [{ date: "2024-02-01", action: "issued", note: "First batch" }],
  },
  {
    id: "card_007",
    cardNumber: "RESQID-2024-0007",
    qrCodeId: "RESQID-STU-2024-001240",
    studentId: "stu7",
    studentName: "Reyansh Kumar",
    class: "6",
    section: "A",
    rollNo: "7",
    bloodGroup: "A+",
    status: "active",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-01-20",
    printCount: 1,
    history: [{ date: "2024-01-20", action: "issued", note: "First batch" }],
  },
  {
    id: "card_008",
    cardNumber: "RESQID-2024-0008",
    qrCodeId: "RESQID-STU-2024-001241",
    studentId: "stu8",
    studentName: "Shanaya Das",
    class: "10",
    section: "A",
    rollNo: "18",
    bloodGroup: "O+",
    status: "deactivated",
    issuedDate: "2024-01-20",
    lastPrinted: "2024-01-20",
    printCount: 1,
    history: [
      { date: "2024-01-20", action: "issued", note: "First batch" },
      {
        date: "2024-08-01",
        action: "deactivated",
        note: "Student transferred",
      },
    ],
  },
];

export const MOCK_EMERGENCY_SCANS_TODAY = {
  totalScans: 12,
  emergencyScans: 3,
  testScans: 7,
  unknownScans: 2,
  alertsDelivered: 10,
  alertsFailed: 2,
};

export const MOCK_EMERGENCY_SCANS = [
  {
    id: "escan_001",
    time: "11:30 AM",
    date: "Today",
    studentName: "Priya Sharma",
    studentId: "s10",
    class: "8-A",
    scannedBy: "Unknown Person",
    scannerPhone: "+91 98112 34567",
    location: "Near Main Gate",
    device: "iPhone Safari",
    emergencyType: "emergency",
    alertStatus: "delivered",
    parentResponded: true,
    notes:
      "Student fell during sports. Minor injury. Parents notified and arrived.",
  },
  {
    id: "escan_002",
    time: "10:15 AM",
    date: "Today",
    studentName: "Aarav Sharma",
    studentId: "s1",
    class: "6-A",
    scannedBy: "Staff (Mr. Suresh)",
    scannerPhone: null,
    location: "Playground",
    device: "Android Chrome",
    emergencyType: "emergency",
    alertStatus: "delivered",
    parentResponded: false,
    notes:
      "Student reported breathing difficulty. Inhaler administered. Parents notified.",
  },
  {
    id: "escan_003",
    time: "9:45 AM",
    date: "Today",
    studentName: "Ananya Patel",
    studentId: "s2",
    class: "6-A",
    scannedBy: "Unknown",
    scannerPhone: null,
    location: "Classroom Block",
    device: "iPhone Safari",
    emergencyType: "unknown",
    alertStatus: "failed",
    parentResponded: false,
    notes:
      "QR scanned but no emergency details provided. Attempting to contact.",
  },
  {
    id: "escan_004",
    time: "8:30 AM",
    date: "Today",
    studentName: "Reyansh Kumar",
    studentId: "s7",
    class: "6-A",
    scannedBy: "Admin (Test)",
    scannerPhone: null,
    location: "Admin Office",
    device: "Windows Chrome",
    emergencyType: "test",
    alertStatus: "delivered",
    parentResponded: false,
    notes: "Scheduled QR test - verifying system functionality.",
  },
  {
    id: "escan_005",
    time: "8:15 AM",
    date: "Today",
    studentName: "Diya Reddy",
    studentId: "s4",
    class: "6-A",
    scannedBy: "Admin (Test)",
    scannerPhone: null,
    location: "Admin Office",
    device: "Windows Chrome",
    emergencyType: "test",
    alertStatus: "delivered",
    parentResponded: false,
    notes: "New card activation test.",
  },
  {
    id: "escan_006",
    time: "3:00 PM",
    date: "Yesterday",
    studentName: "Arjun Nair",
    studentId: "s3",
    class: "6-A",
    scannedBy: "Parent (Mrs. Nair)",
    scannerPhone: "+91 98765 43210",
    location: "School Gate",
    device: "Android Chrome",
    emergencyType: "emergency",
    alertStatus: "delivered",
    parentResponded: true,
    notes: "Parent scanned to pick up child early due to family emergency.",
  },
  {
    id: "escan_007",
    time: "12:00 PM",
    date: "Yesterday",
    studentName: "Unknown Student",
    studentId: null,
    class: "—",
    scannedBy: "Unknown",
    scannerPhone: null,
    location: "Back Gate",
    device: "Android",
    emergencyType: "unknown",
    alertStatus: "failed",
    parentResponded: false,
    notes: "Unregistered QR code scanned. No student match found.",
  },
  {
    id: "escan_008",
    time: "9:00 AM",
    date: "Yesterday",
    studentName: "Kavya Joshi",
    studentId: "s6",
    class: "6-A",
    scannedBy: "Admin (Test)",
    scannerPhone: null,
    location: "Admin Office",
    device: "Windows Chrome",
    emergencyType: "test",
    alertStatus: "delivered",
    parentResponded: false,
    notes: "Routine weekly QR test.",
  },
];

export const MOCK_ANOMALY_STATS = {
  total: 24,
  open: 7,
  resolvedToday: 5,
  highSeverity: 3,
};

export const MOCK_ANOMALIES = [
  {
    id: "ANO-001",
    type: "duplicate_scan",
    severity: "high",
    status: "open",
    student: "Priya Sharma",
    studentId: "STU-2341",
    class: "8-A",
    avatar: "PS",
    avatarColor: "bg-blue-500",
    description:
      "QR card scanned twice within 4 minutes at two different gates",
    location: "Gate A → Gate C",
    time: "8:02 AM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-002",
    type: "unknown_card",
    severity: "high",
    status: "open",
    student: "Unknown",
    studentId: null,
    class: "—",
    avatar: "?",
    avatarColor: "bg-slate-400",
    description: "Unregistered QR card scanned at main entrance",
    location: "Main Entrance",
    time: "8:17 AM",
    date: "Today",
    detectedBy: "Gate Scanner #1",
  },
  {
    id: "ANO-003",
    type: "outside_hours",
    severity: "medium",
    status: "open",
    student: "Rahul Gupta",
    studentId: "STU-1892",
    class: "11-B",
    avatar: "RG",
    avatarColor: "bg-indigo-500",
    description: "Student scanned card 2 hours after school ended",
    location: "Back Gate",
    time: "5:45 PM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-004",
    type: "multiple_exits",
    severity: "medium",
    status: "investigating",
    student: "Dev Chatterjee",
    studentId: "STU-4201",
    class: "9-B",
    avatar: "DC",
    avatarColor: "bg-amber-500",
    description:
      "Student recorded exiting campus 3 times in one day without re-entry",
    location: "Gate B",
    time: "11:30 AM",
    date: "Today",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-005",
    type: "suspicious_timing",
    severity: "low",
    status: "open",
    student: "Sneha Bose",
    studentId: "STU-3012",
    class: "7-C",
    avatar: "SB",
    avatarColor: "bg-rose-500",
    description: "Card scanned 35 minutes before school gates officially open",
    location: "Main Entrance",
    time: "6:55 AM",
    date: "Today",
    detectedBy: "Gate Scanner #1",
  },
  {
    id: "ANO-006",
    type: "duplicate_scan",
    severity: "high",
    status: "resolved",
    student: "Arjun Sharma",
    studentId: "STU-2342",
    class: "5-B",
    avatar: "AS",
    avatarColor: "bg-violet-500",
    description: "Same QR card used simultaneously at Gate A and Gate B",
    location: "Gate A + Gate B",
    time: "7:58 AM",
    date: "Yesterday",
    detectedBy: "Auto-detection",
  },
  {
    id: "ANO-007",
    type: "unknown_card",
    severity: "medium",
    status: "resolved",
    student: "Unknown",
    studentId: null,
    class: "—",
    avatar: "?",
    avatarColor: "bg-slate-400",
    description: "Deactivated student card attempted access",
    location: "Side Gate",
    time: "3:12 PM",
    date: "Yesterday",
    detectedBy: "Gate Scanner #3",
  },
  {
    id: "ANO-008",
    type: "outside_hours",
    severity: "low",
    status: "resolved",
    student: "Kavya Nair",
    studentId: "STU-5101",
    class: "6-A",
    avatar: "KN",
    avatarColor: "bg-pink-500",
    description: "Student scanned in on a school holiday",
    location: "Main Entrance",
    time: "9:15 AM",
    date: "2 days ago",
    detectedBy: "Auto-detection",
  },
];

export const MOCK_SCAN_LOGS = [
  {
    id: "scan_001",
    time: "8:12 AM",
    studentName: "Aarav Sharma",
    studentId: "STU-2342",
    class: "5-B",
    rollNo: 1,
    gate: "Main Gate Scanner",
    deviceId: "dev1",
    type: "attendance",
    status: "success",
    cardId: "RFID-001",
    flag: null,
    date: "Today",
  },
  {
    id: "scan_002",
    time: "8:14 AM",
    studentName: "Ananya Patel",
    studentId: "STU-2343",
    class: "6-A",
    rollNo: 2,
    gate: "Main Gate Scanner",
    deviceId: "dev1",
    type: "attendance",
    status: "success",
    cardId: "RFID-002",
    flag: null,
    date: "Today",
  },
  {
    id: "scan_003",
    time: "9:05 AM",
    studentName: "Arjun Nair",
    studentId: "s3",
    class: "6-A",
    rollNo: 3,
    gate: "Side Gate Scanner",
    deviceId: "dev2",
    type: "attendance",
    status: "late",
    cardId: "RFID-003",
    flag: null,
    date: "Today",
  },
  {
    id: "scan_004",
    time: "8:10 AM",
    studentName: "Diya Reddy",
    studentId: "s4",
    class: "6-A",
    rollNo: 4,
    gate: "Main Gate Scanner",
    deviceId: "dev1",
    type: "attendance",
    status: "success",
    cardId: "RFID-004",
    flag: null,
    date: "Today",
  },
  {
    id: "scan_005",
    time: "8:00 AM",
    studentName: "Priya Sharma",
    studentId: "STU-2341",
    class: "8-A",
    rollNo: 12,
    gate: "Gate A",
    deviceId: "dev4",
    type: "attendance",
    status: "duplicate",
    cardId: "RFID-042",
    flag: "suspicious",
    date: "Today",
  },
  {
    id: "scan_006",
    time: "8:17 AM",
    studentName: "Unknown",
    studentId: null,
    class: "—",
    rollNo: null,
    gate: "Main Gate Scanner",
    deviceId: "dev1",
    type: "unknown",
    status: "invalid",
    cardId: "UNREG-042",
    flag: "suspicious",
    date: "Today",
  },
  {
    id: "scan_007",
    time: "5:45 PM",
    studentName: "Rahul Gupta",
    studentId: "STU-1892",
    class: "11-B",
    rollNo: 7,
    gate: "Back Gate",
    deviceId: "dev3",
    type: "attendance",
    status: "success",
    cardId: "RFID-019",
    flag: null,
    date: "Today",
  },
  {
    id: "scan_008",
    time: "11:30 AM",
    studentName: "Dev Chatterjee",
    studentId: "STU-4201",
    class: "9-B",
    rollNo: 6,
    gate: "Gate B",
    deviceId: "dev2",
    type: "attendance",
    status: "success",
    cardId: "RFID-020",
    flag: null,
    date: "Today",
  },
];
